
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import ContactUs from './components/ContactUs';
import './globals.css';
import { ThemeProvider } from '@mui/material/styles';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
const inter = Inter({ subsets: ['latin'] });
import getLPTheme from './theme';
import NavBar from './components/Navbar';
import { Box, CssBaseline } from '@mui/material';
import Footer from './components/FooterSection';
export const metadata: Metadata = {
  title: 'Hackspire 2024',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className={inter.className}>
        <AppRouterCacheProvider>
          <CssBaseline />
          <Box
            sx={{width: '100%',backgroundImage: 'linear-gradient(90deg,#000000,#0a085c)', backgroundSize: '100% 100%',
            backgroundRepeat: 'no-repeat',
          }}
          >
            <NavBar />
            {children}
            <ContactUs />
            <Footer />
          </Box>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
